### ISSUE TITLE
syntax error in testcrt.py

### ISSUE THREAD

**Issue by ydufresne** [google/cloudprint_logocert#10]
1) Using latest testcrt.py, and updated files, getting the following syntax error
./testcert.py
./testcert.py: line 5: syntax error near unexpected token `newline'
./testcert.py: line 5: `<!DOCTYPE html>'

2) The format of _config.py has changed significantly.  Are the instructions in the README file still valid?

**Comment by YasuhiroFuruta-EPSON** [comment]
1) Using latest testcrt.py, and updated files, getting the following syntax error
I think you downloaded the 'testcert.py' as HTML.
I recommend using the 'Download ZIP' button to download.

**Comment by YasuhiroFuruta-EPSON** [comment]
2) The format of _config.py has changed significantly. Are the instructions in the README file still valid?
The '_config.py' has not been changed from the first commit except for some capability variables on the CAPS field.
See the comments of each capability variables for now.

**Comment by ydufresne** [comment]
re-downloaded zip with new content worked properly.
