### ISSUE TITLE
logocert_api branch: (Propose) testLocalDiscoveryToggle()

### ISSUE THREAD

**Issue by YoshimiMorita** [google/cloudprint_logocert#100]
Hi Kelly-san/Kevin-san/GCPTeam,

About testLocalDiscoveryToggle() test:

In some printers,
when toggled off local discovery, local printing will toggle off (disabled) too.

So that, local printing may remain OFF (disabled) after this test.
Then, subsequent 'LocalPrinting' test suite will be failed.

I think that it is necessary to explicitly process to enable local printing.

Regards,
Yoshimi Morita

**Comment by kdlucas** [comment]
Yoshimi-san,

We discussed this internally and decided to put a post test check in to see what state Local Printing is in, and to toggle is back if it's still turned off. We've seen various behavior with different printers, so it seems a check is needed.

**Comment by lrbom** [comment]
Yoshimi-san,

Thanks for bringing this to our notice.
As Kelly said, we have added a check to make sure local printing remains on after the testLocalDiscoveryToggle() test. Please pull and give it a try.

Thanks,
Kevin

**Comment by YoshimiMorita** [comment]
Hi Kelly-san/Kevin-san,

I confirm this change, it works well.
Thank you for accepting my proposal.

I will close this.

Thanks,
Yoshimi Morita
