### ISSUE TITLE
GCP 2.0 version Certification does not contain mdns.py

### ISSUE THREAD

**Issue by nprasadwa** [google/cloudprint_logocert#101]
We found the below modules list contains “mdns.py” for document, but cloudprint_logocert-logocert_api file has no this python instead of “zconf.py”, could you help to confirm with the designer if anything incorrect?

Please advise as this missing mdns.py file always shows, "No printers discovered under HP xx"

**Comment by lrbom** [comment]
Hi,

I am the developer for the logocert_api branch.

There was a mistake in the README which has been addressed, zconf.py has in fact replaced mdns.py. Thanks for pointing it out! 

As for the issue with the tool not detecting any Privet advertisements, if you are running the tool on a workstation that is on the network as the printer, you should be able to see all the powered on Privet-enabled printers on that network.

 Example logging looks like this:
   LogoCert INFO: Got new access token.
   LogoCert INFO: Service added: "HP LaserJet 400 M401dw (B7AF95)._privet._tcp.local."
   LogoCert INFO: Service added: "Printer2._privet._tcp.local."
   LogoCert INFO: Service added: "Printer3._privet._tcp.local."
   LogoCert INFO: All listeners have been stopped.

Please pull again from logocert_api, check for any network issues and try again.
Sorry for the lack of direct resolution but I look forward to hearing back from you if the issue persists. 

Thanks,
Kevin

**Comment by kdlucas** [comment]
I think the updated README should address this issue. Closing.
