### ISSUE TITLE
testChromePrintCopies Failing On Chrome 56.0.2924.87

### ISSUE THREAD

**Issue by dansinadjan** [google/cloudprint_logocert#103]
The changes in Chrome 56.0.2924.87 is causing the testChromePrintCopies to fail because the test couldn't locate the increment button.
![screen shot 2017-03-09 at 5 01 25 pm](https://cloud.githubusercontent.com/assets/26297839/23743029/1848685a-04ea-11e7-8e0d-3c106b9fd555.png)

On Chrome v54, the Copies field looked like this:
![image](https://cloud.githubusercontent.com/assets/26297839/23743059/2d7780c6-04ea-11e7-8b4d-253ac1f70acc.png)

On the recent versions, the field looks like this:
![image](https://cloud.githubusercontent.com/assets/26297839/23743063/32365542-04ea-11e7-8c96-4a05983cc5e9.png)

The newer version of Chrome is using an input type="number" instead of an input type="text" in the previous version. With the removal of the +/- buttons, the test is unable to locate the element with a class="increment" and fails.

Changes should be made in SetCopiesInPrintDialog() in _chrome.py.

**Comment by kdlucas** [comment]
Please download the logocert_api branch and try that version of the Logo
Certification Tool.

Kelly
kdLucas

**Comment by dansinadjan** [comment]
That version works. Thanks.
