### ISSUE TITLE
Failure during the Registration test suite prevents the cert tool from continuing

### ISSUE THREAD

**Issue by tblossfeld** [google/cloudprint_logocert#105]
Currently, we are failing the RegistrationMultipleUsers test (we are looking into this on our end). A side effect of failing this test is that the cert tool is unable to continue through the rest of the Registration test suite. This means testers must manually register the printer in order to proceed into the next suite of tests.

Screenshot attached:
![screenshot from 2017-03-13 102037](https://cloud.githubusercontent.com/assets/17885939/23858651/8923668e-07d7-11e7-867a-20db2f20f319.png)

**Comment by lrbom** [comment]
Hi,

Thanks for running the new tool and providing feedback.

This error you are seeing seems valid. 
On the local side of things, registration is a 3 step process that occurs over the Privet API: 
- start
- getClaimToken
- complete

In a normal single user registration scenario, the 3 APIs are called in succession in the order listed above. Even in the normal case, getClaimToken returns the error message, 'pending_user_action', to signal that the printer is waiting for the user to manually accept/cancel the registration on the printer's UI. So this pending_user_action error message is not really indicative of actual failure. 

For this simultaneous registration test case, the order of operation is as follows:
1. User1 - /privet/register/?action=start (Expect success)
2. **_User2_** - /privet/register/?action=start (Expect success)
3. **_User2_** - /privet/register/?action=getClaimToken (Expect error but NOT pending_user_action error)
4. User1 - /privet/register/?action=getClaimToken (Expect pending_user_action error or success)

 

The printer should be rejecting User2's call to getClaimToken with an error message indicative of failure. The 'pending_user_action' error message is benign. 

Hope this helps with your debugging.

Thanks,
Kevin

From https://developers.google.com/cloud-print/docs/privet#43-privetregister-api:
![image](https://cloud.githubusercontent.com/assets/23246871/23870339/5b519c06-07e3-11e7-80f0-33b4fd0e3739.png)

**Comment by tblossfeld** [comment]
Yes, this very helpful for our debugging purposes. Thank you!

I also wanted to bring this to your attention because it seems as though there might be a bug within the cert tool where it does not continue running after this test fails. It seems as though there should be more than two tests within the Registration section of the cert tool. However, after this failure, the cert tool stops running. The only way to get past it is to manually register the printer and remove Registration from the list of tests to be run in the _config.py file.

**Comment by kdlucas** [comment]
One issue with the Registration test failing is that many of the tests are
dependent on the printer being registered, so I believe this is by design.

Kelly
kdLucas

**Comment by lrbom** [comment]
Yes, as Kelly said, it's by design that tests are separated by the printer's registration state.
In the case that the Registration suite is failing, you may still continue testing all the other suites after manually registering the printer.

As for the Registration suite itself, it only contains 1 test case; however, the test case itself contains 3 separate tests. There are several of these composite test cases in the cert tool. For those composite test cases, if a prerequisite test fails the following tests are not run. This should be fine since the user is encouraged to fix the issue and re-run the test until it passes.

**Comment by tblossfeld** [comment]
Ah, ok then. Thanks for the responses!
