### ISSUE TITLE
(logocert_api) RunAfter24Hours Fails — Asking User Credentials?

### ISSUE THREAD

**Issue by dansinadjan** [google/cloudprint_logocert#106]
RunAfter24Hours fails if run for a full 24 hours:
![24hours](https://cloud.githubusercontent.com/assets/26297839/24396452/d814b8f6-13d5-11e7-8a3e-a5b42e02961e.png)

Is this a setup issue? I'm seeing that the call _device.GetDeviceDetails() fails to get data from the server and is requiring "User credentials."

Thanks.

**Comment by lrbom** [comment]
Hi,

This is actually a bug where an expired access token is used for a Privet API call. Good find! 
The access token has an expiry time of 1 hour so it's become invalid after the 24 hour sleep.
This is addressed now, please pull from logocert_api and let me know if the issue persists.

Link to the  fix: https://github.com/google/cloudprint_logocert/commit/1061c536cc5a4a0d58cbe49866369ff5b56161a6

Cheers,
Kevin

**Comment by dansinadjan** [comment]
Verified that this is fixed. Thanks.
