### ISSUE TITLE
LocalPrinting: testLocalPrintUpdateMgtPage not found

### ISSUE THREAD

**Issue by lookarliu** [google/cloudprint_logocert#114]
A case for "Local print job should updated on the Google Cloud Management page" is not found in the testcert.py

**Comment by vamshikk** [comment]
Hi Lookar,

In the current release, the 'testLocalPrintUpdateMgtPage' test has been moved into manual testing. For a list of manual tests, please take a look at the On boarding document 'Manual Tests' sheet.

**Comment by vamshikk** [comment]
This test is automated now and has been added. It is a part of the Local Printing suite.
