### ISSUE TITLE
PrinterState() suite Failure

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#124]
This issue related to #121 and #123.

Our printer fails testNoMediaInTray() and testTonerCartridge().
Because these test cases check 'input' or 'tray' is in 'caption' field or 'message' field field in CDS, but the paper source is called 'Cassette 1' in 'caption' field or 'message' field on this printer.

I think other test cases which call VerifyUiStateMessage() have the same problem.

In addition, this printer passed these tests at 30e56a1b2509a6e7aadf1ebc2371484e103367d1.

How to fix it?
Please give your opinion.

**Comment by lrbom** [comment]
Regarding testNoMediaInTray(), I've pushed this commit which now accepts "cassette" as a required keyword: https://github.com/google/cloudprint_logocert/commit/dd0583c806cc3f659eb8542be69c179340b2397d

Please let me know the error you get for testTonerCartridge() as that test case does not check for input/tray, it checks for ink/toner.

**Comment by YasuhiroFuruta** [comment]
Thank you for your changes.
dd0583c806cc3f659eb8542be69c179340b2397d works fine with my printer.
testTonerCartridge() works fine before/after dd0583c806cc3f659eb8542be69c179340b2397d.
