### ISSUE TITLE
Some Cloudprinting test cases is confusing.

### ISSUE THREAD

**Issue by marctan** [google/cloudprint_logocert#125]
The test cases are below:
test_22_CloudPrintFileMultiPagePdf
test_23_CloudPrintFileLargeColorPdf
test_30_CloudPrintFilePdfColorTicket
test_33_CloudPrintFilePdfColorTest
test_40_CloudPrintFileColorPngLandscape
test_42_CloudPrintFilePngColorImageWithText

These test cases are asking users/testers if the printouts were printed in "colors" (via logger.info display). This is confusing to the users if the printer used is a 'mono' printer. 

I think this test cases should be skipped if 'COLOR' options in config.py is set to false.

Thoughts?

Thanks!
Marc

**Comment by vamshikk** [comment]
Thank you for your feedback Marc. logger.info displays the information being logged into the log file.

What you see in 'LogoCert INFO: Name: ' line is the name of the test case in the test plan. In these test cases, the input document type being printed and its characteristics (multi page, large, Landscape etc). For monochrome printers, we expect only black and white printouts. 

These test cases are essential and need to be run for all printers. Let me know if you need further clarification.

Thanks,
Vamshi

**Comment by marctan** [comment]
Thanks for the reply vamshikk. So if the printer used is monochrome and the loger.info is showing **'LogoCert INFO: Printing _Color_ PNG file in landscape'** as you can see from the screenshot below: 
![untitled](https://user-images.githubusercontent.com/19194749/27208356-bf63ce06-5277-11e7-9eeb-767cb8a56245.png) 

The expected result is, it will print in black & white not in Color. So the tester should enter "Y".  Am I correct?

Thanks!

**Comment by vamshikk** [comment]
Yes, that is correct. The 'LogoCert INFO: ' line is describing what source file the test tool is using. The expected result here is a landscape orientation print. For a monochrome printer, the output expected is black and white.

**Comment by marctan** [comment]
Got it. It's clear now.  Thanks!
