### ISSUE TITLE
The test after PostRegistration() might be failed

### ISSUE THREAD

**Issue by YoshimiMorita** [google/cloudprint_logocert#128]
In the 'Privet.PowerOffRegistered' test of PostRegistration:

It does not wait until the device status is back 'online', finally.
So that, when the next test runs while the device is connecting to the server (the device status is not online), it will be failed.
Example: Run LocalDiscovery() right after PostRegistration()

I think that it is necessary to wait until the device status is back 'online', in the 'Privet.PowerOffRegistered' test.

**Comment by lrbom** [comment]
I've pushed a commit that fixes this: https://github.com/google/cloudprint_logocert/commit/3f2ba4016575b4478d26c7187c08f225914676da

Thanks for raising this issue!

**Comment by YoshimiMorita** [comment]
Thank you for your change. It works well.
This issue was fixed.
