### ISSUE TITLE
I suddenly can't make testNoMediaInTray Pass

### ISSUE THREAD

**Issue by dansinadjan** [google/cloudprint_logocert#129]
Wasn't there supposed to be a message that appears here when I remove all media from the device?
![screen shot 2017-07-04 at 8 53 17 pm](https://user-images.githubusercontent.com/26297839/27830878-f231b8b6-60fa-11e7-9e1b-80eea2cf3719.png)

I've run this test this morning and all were fine. This afternoon, I can't seem to make this specific test pass. I've been using the same device to run the test so I'm sure that my setup is the same. Also, I can see these messages:
![screen shot 2017-07-04 at 8 52 53 pm](https://user-images.githubusercontent.com/26297839/27830919-1983d750-60fb-11e7-8dce-bdc2ffd4b32a.png)

Did something change with the servers? Do you think there is something wrong with my device?

Thanks.

**Comment by dansinadjan** [comment]
Just now I tried it again and it's passing. I don't know what just happened! I did not touch my setup.

**Comment by lrbom** [comment]
Please attach logs next time this happens again. It could be a case of the printer being in a state with multiple errors so the expected error wasn't detected.

**Comment by dansinadjan** [comment]
This issue hasn't happen in a while. Closing this issue and will reopen if ever the problem is seen again.

Thanks.
