### ISSUE TITLE
No long edge/short edge support in Chrome print dialog

### ISSUE THREAD

**Issue by bohao-wei** [google/cloudprint_logocert#130]
Chrome version: Version 59.0.3071.115

No long edge/short edge support in Chrome print dialog, some test cases with long edge/short edge option may fail.

![tss](https://user-images.githubusercontent.com/16394934/27983805-23f4776c-63f8-11e7-862b-5916436e2f70.jpg)

**Comment by lrbom** [comment]
Hi,

The Logocert tool has been updated to function independent of Chrome.
The long/short edge test cases should work since the tool now calls the APIs directly.

Please pull from the 'master' branch and try it out!

Thanks,
Kevin

**Comment by bohao-wei** [comment]
It's OK now, thank you.
