### ISSUE TITLE
GCP Tool Questions, version 2

### ISSUE THREAD

**Issue by nprasadwa** [google/cloudprint_logocert#133]
1.  “Margins” and “Fit to page” options do not support on GCP2.0 when aligned with Google before. But the specification has not stated this change, while our GCP test cases still include these options and they still show on GCP three methods coverage. Please help to confirm this.

2.  The Google API version should be 2.0 after new GCP certification fixed, is it right? At present, Kronos Refresh WL ST_FW1728D still shows 1.0 version on Google Simulate Page as well as API page, is this as expected? Please help to share the validation method. Thanks. 

3.  Could you provide Enterprise printers list to us? We are not very clear about this. 

4.  When open these formats (html/svg/tif) from Drive app using mobile device(Android version:5.0.2), it has no “Print” icon. This issue does not occur on other formats. Could you help to confirm on it? Thanks.

5.  In page 18 , “The 2.x service provides backwards compatibility with 1.x devices, but a number of additional features and properties are available with 2.x services.”  What does that means for “A number of additional features and properties” and what we could be tested?

6.  Enable Cloud Print | Device provides UI to enable   Cloud Print functionality. | Enable Cloud Print   functionality.
-- | -- | --
RESULTS:
Disable Cloud Print | Device provides UI to disable Cloud Print functionality. | 1. ****Registered, then disable   Cloud Print functionality, the printer is deleted.****  [THIS IS THE QUESTION]
-- | -- | -- No   registered, then disable cloud  print functionality, the printer could   not register.

7.  Job Completion | Device must issue a /control request with status DONE or ERROR.   This must occur within 2 seconds of job completion. | 1.The job state should be   changed to Printed after refresh webpage
-- | -- | --
RESULTS:  The   job state does not change if do not any action and wait for 5 minutes when   complete to print job.(Google chrome browse version: 59.0.3071.115(Official   Build)  [THIS IS THE QUESTION]

8.   Issue request to http://<device_ip>/privet/info with header set to: X-Privet-Token: “”
version: <2.0 or higher> | 10. version: 1.0  [THIS IS THE QUESTION]

Thank you,
Nilesh

**Comment by kdlucas** [comment]
Nilesh,

My guess is you took this up with someone on the GCP team by now, as this site is only for the Logo Certification Tool. I'm going to close this out. If there are existing issues with the tool please open individual issues with each issue for the tool.
