### ISSUE TITLE
fails testJobStateMissingToner()

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#136]
Our printer fails testJobStateMissingToner() because it does not start the job while ink error.
(We think it's better not to start the job while ink error because user possibly turn off the printer while ink error.)

I think that it's better to change testJobStateMissingToner() to make an ink error after the job started.

**Comment by lrbom** [comment]
Can you please provide some logs from that printer running this test case? Do you mean that your jobs are getting into QUEUED state instead of STOPPED?

**Comment by YasuhiroFuruta** [comment]
The cause of this issue was our operation error.

Our printers accept GCP job even if they are under error condition.
And our printer passed this test case.

Sorry for the trouble.
