### ISSUE TITLE
fails testJobStateWithPaperJam()

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#137]
Our printer fails testJobStateWithPaperJam() because a previous job which cause jam error is active and a job which is submitted by the tool does not be started.

I think that testJobStateWithPaperJam() should be changed to make jam error while printing the job which submitted by the tool.

**Comment by lrbom** [comment]
Hi,

Can you please try cancelling/deleting the job via the GCP management page after causing the paper jam? This way, the next job can be started and the test can validate that it properly goes into the STOPPED state.

Thanks,
Kevin

**Comment by YasuhiroFuruta** [comment]
Please excuse my lack of explanation.
The previous job is a standalone copy job to produce paper jam state, it's not an GCP job.
(Our printer does not detect paper jam under idle state.)
However, our printer does not start any GCP job while error state even if the previous job is canceled.

Reporting paper jam is not required before starting job in this testcase.
I think it's good to change the prompt message as follows.
"Press ENTER once ~~printer reports paper jam~~ **paper is placed inside print path**."

**Comment by lrbom** [comment]
Regarding:

> "However, our printer does not start any GCP job while error state even if the previous job is canceled."

When a GCP printer is in an error state, the /submit call to the GCP servers should still succeed but the job itself may be queued or stopped. Can you please provide the console output + google sheet logs for this test case?

Thanks,
Kevin

**Comment by YasuhiroFuruta** [comment]
The cause of this issue was our operation error and our network problem.

Our printers accept GCP job even if they are under error condition.
And our printer passed this test case.

Sorry for the trouble.

**Comment by lrbom** [comment]
Thanks for confirming. No problem at all!
