### ISSUE TITLE
1.6.34 NotInCDD.margins failed

### ISSUE THREAD

**Issue by jiape** [google/cloudprint_logocert#139]
Goal/Objective:Verify margins is not a CDD capability.

We don't have margins in CDD, but scripts return failed.

Can you help confirm is this the scripts issue.

Thanks,
Andy

**Comment by lrbom** [comment]
Hi Andy,

Please provide both console output + Google sheet output for that test case so I can help debug this issue for you.

Thanks,
Kevin

**Comment by 18721981366** [comment]
Hi Kevin,

Thanks for your help.

**Google sheet output:**

7d60c7c7-08ed-45f2-9e39-1a50d45467a6 | OptionalInCDD.margins | Failed | "margins"   not found in printer capabilities. Ensure the Margins option in _config.py is   correctly set.
-- | -- | -- | --


**Here is the console output:**
Verify margin is appropriately set/unset in printer capabilities.
 ... 

_device.cdd['caps'] = {u'page_orientation': {u'option': [{u'is_default': True, u'type': u'PORTRAIT'}, {u'type': u'LANDSCAPE'}, {u'type': u'AUTO'}]}, u'duplex': {u'option': [{u'is_default': True, u'type': u'NO_DUPLEX'}]}, u'color': {u'option': [{u'is_default': True, u'type': u'STANDARD_MONOCHROME'}]}, u'media_size': {u'option': [{u'is_continuous_feed': False, u'width_microns': 215900, u'vendor_id': u'NorthAmericaLetter', u'is_default': True, u'height_microns': 279400, u'custom_display_name': u'LETTER', u'name': u'NA_LETTER'}, {u'is_continuous_feed': False, u'width_microns': 210000, u'vendor_id': u'ISOA4', u'is_default': False, u'height_microns': 297000, u'custom_display_name': u'A4', u'name': u'ISO_A4'}, {u'is_continuous_feed': False, u'width_microns': 148000, u'vendor_id': u'ISOA5', u'is_default': False, u'height_microns': 210000, u'custom_display_name': u'A5', u'name': u'ISO_A5'}, {u'is_continuous_feed': False, u'width_microns': 105000, u'vendor_id': u'ISOA6', u'is_default': False, u'height_microns': 148000, u'custom_display_name': u'A6', u'name': u'ISO_A6'}]}, u'cover': [{u'vendor_id': u'Door', u'type': u'DOOR', u'custom_display_name': u'Door'}], u'copies': {u'default': 1, u'max': 999}, u'output_bin_unit': [{u'vendor_id': u'outputBin', u'type': u'OUTPUT_BIN', u'custom_display_name': u'Output Bin'}], u'media_path': [{u'vendor_id': u'paperPath'}], u'pwg_raster_config': {u'document_sheet_back': u'NORMAL', u'document_resolution_supported': [{u'feed_dir': 300, u'cross_feed_dir': 300}, {u'feed_dir': 600, u'cross_feed_dir': 600}], u'document_type_supported': [u'SGRAY_8']}, u'marker': [{u'color': {u'type': u'BLACK', u'custom_display_name': u'BLACK'}, u'vendor_id': u'black', u'type': u'TONER', u'custom_display_name': u'Black Cartridge'}], u'input_tray_unit': [{u'vendor_id': u'tray', u'type': u'INPUT_TRAY', u'custom_display_name': u'Input Tray'}], u'supported_content_type': [{u'content_type': u'image/pwg-raster'}], u'dpi': {u'option': [{u'is_default': True, u'vertical_dpi': 600, u'horizontal_dpi': 600}]}}

The Margins option in _config.py set to True, so "margins" is expected in the CDD

LogoCert INFO: Test ID: 7d60c7c7-08ed-45f2-9e39-1a50d45467a6
LogoCert INFO: Result: Failed
LogoCert INFO: Name: OptionalInCDD.margins
LogoCert INFO: Notes: "margins" not found in printer capabilities. Ensure the Margins option in _config.py is correctly set.
FAIL
testCapsMarker (__main__.Printer)

**Comment by lrbom** [comment]
Thanks for the provided information.

The script now checks for the presence/absence of "margins" in the CDD depending on the value you set in _config.py. Since your have set MARGINS as True in _config.py, the script now checks that "margins" is present in the CDD. 

This is a different behavior from the previous logocert tool and also the test tracker test description (it should have been updated when this script adopted the new change). Sorry for the confusion! 

Please let me know if you have further questions.

**Comment by 18721981366** [comment]
Hello,

That we support GCP.Margins, so we cannot set "MARGINS" as False. 
1.8.15 GCP.Margins
Goal/Objective:Verify Printer Margins option for a GCP print job

**Comment by lrbom** [comment]
If your printer indeed supports GCP.Margins, then you should set "MARGINS" as true in _config.py.
However, since your printer supports margins, the "margins" field should be present in the CDD.
Perhaps you are missing this field in your CDD.

**Comment by lrbom** [comment]
Hi Andy,

Sorry, I'm not familiar with Chrome's behavior. It's possible that Chrome can alter the print job via software so the option is present. Our main concern is that your printer is exposing the correct fields in its CDD.
 
To clarify, if your printer does not support Margins, then it should not have the margins field in the CDD. Conversely, if your printer supports Margins, then it should definitely have the margins field in the CDD.

Thanks,
Kevin

**Comment by jiape** [comment]
Hi Kevin,

Thanks for your information.

Regards,
Andy
