### ISSUE TITLE
PrivetRegistration.PrinterPanelCancel/PrivetAPI.RegistrationInvalidUserAuthToken failed

### ISSUE THREAD

**Issue by jiape** [google/cloudprint_logocert#140]
Our printer is the button LED control panel, only have OK button on it.
Test case "PrivetRegistration.PrinterPanelCancel" will be skipped if set PRINTER_PANEL_UI to false, the final results are passed. but test case "PrivetAPI.RegistrationInvalidUserAuthToken" will be failed because PRINTER_PANEL_UI is false that scripts will not prompt user to click OK button on control panel.

Can you help check to see if google can change the scripts or we can click the OK button while run this test?

Thanks,
Andy

**Comment by lrbom** [comment]
Hi Andy,

I have pushed up a change that should address your issue. https://github.com/google/cloudprint_logocert/commit/c199006ea578c81e4bb88ecd1e2e73bfe0b817a6

Please pull from master, keep the 'PRINTER_PANEL_UI' flag as true, and run both of the tests you mentioned. Let me know if that works for you.

Thanks,
Kevin

**Comment by jiape** [comment]
Hi Kevin,

Thanks for making change on the scripts. it works now.

Andy
