### ISSUE TITLE
CDD.duplex failed

### ISSUE THREAD

**Issue by jiape** [google/cloudprint_logocert#141]
1. We are running the Printer test suite with the printer which is not support duplex.
2. We have 'duplex' in CDD, but we set the "Type" as "NO_DUPLEX".
3. Noticed that final results of Printer suite is ok, there is no failure prompt.

Can you help confirm is this ok that we have 'duplex' in CDD with type "NO_DUPLEX"? or we need totally remove 'duplex' in CDD which the printer is not support duplex?

Test Logs:
Verify duplex is in printer capabilities.
 ... _device.cdd['caps'] = {u'page_orientation': {u'option': [{u'is_default': True, u'type': u'PORTRAIT'}, {u'type': u'LANDSCAPE'}, {u'type': u'AUTO'}]}, u'duplex': {u'option': [{u'is_default': True, u'type': u'NO_DUPLEX'}]}, u'color': {u'option': [{u'is_default': True, u'type': u'STANDARD_MONOCHROME'}]}, u'media_size': {u'option': [{u'is_continuous_feed': False, u'width_microns': 215900, u'vendor_id': u'NorthAmericaLetter', u'is_default': True, u'height_microns': 279400, u'custom_display_name': u'LETTER', u'name': u'NA_LETTER'}, {u'is_continuous_feed': False, u'width_microns': 210000, u'vendor_id': u'ISOA4', u'is_default': False, u'height_microns': 297000, u'custom_display_name': u'A4', u'name': u'ISO_A4'}, {u'is_continuous_feed': False, u'width_microns': 148000, u'vendor_id': u'ISOA5', u'is_default': False, u'height_microns': 210000, u'custom_display_name': u'A5', u'name': u'ISO_A5'}, {u'is_continuous_feed': False, u'width_microns': 105000, u'vendor_id': u'ISOA6', u'is_default': False, u'height_microns': 148000, u'custom_display_name': u'A6', u'name': u'ISO_A6'}]}, u'cover': [{u'vendor_id': u'Door', u'type': u'DOOR', u'custom_display_name': u'Door'}], u'copies': {u'default': 1, u'max': 999}, u'output_bin_unit': [{u'vendor_id': u'outputBin', u'type': u'OUTPUT_BIN', u'custom_display_name': u'Output Bin'}], u'media_path': [{u'vendor_id': u'paperPath'}], u'pwg_raster_config': {u'document_sheet_back': u'NORMAL', u'document_resolution_supported': [{u'feed_dir': 300, u'cross_feed_dir': 300}, {u'feed_dir': 600, u'cross_feed_dir': 600}], u'document_type_supported': [u'SGRAY_8']}, u'marker': [{u'color': {u'type': u'BLACK', u'custom_display_name': u'BLACK'}, u'vendor_id': u'black', u'type': u'TONER', u'custom_display_name': u'Black Cartridge'}], u'input_tray_unit': [{u'vendor_id': u'tray', u'type': u'INPUT_TRAY', u'custom_display_name': u'Input Tray'}], u'supported_content_type': [{u'content_type': u'image/pwg-raster'}], u'dpi': {u'option': [{u'is_default': True, u'vertical_dpi': 600, u'horizontal_dpi': 600}]}}
_device.cdd['caps']['duplex'] = {u'option': [{u'is_default': True, u'type': u'NO_DUPLEX'}]}

LogoCert INFO: Test ID: 75fbbffe-5530-4523-a4b8-4dfd0b9aee08
LogoCert INFO: Result: Failed
LogoCert INFO: Name: CDD.duplex
LogoCert INFO: Notes: Error in _config file, DUPLEX should be True
ok
testCapsFitToPage (__main__.Printer)

**Comment by lrbom** [comment]
Hi,

Thanks for the detailed logs and writeup on the issue.

I have added the the check in the logocert 2.0 as a safety mechanism in case the user mistakenly sets 'DUPLEX' to false in _config.py. I realize that the check is a bit harsh, so I have loosened the constraint a bit. I have updated the script to only warn the user if more than 1 options are found in the CDD under 'duplex': https://github.com/google/cloudprint_logocert/commit/90651ce38a8283c83f0a63a0ff612478bc2c6bed

Please pull from master and verify that your printer is now correctly marking the test as 'SKIPPED'.

Thanks,
Kevin

**Comment by jiape** [comment]
Hi Kevin,

Thank you for making change on the scripts, now the test as "SKIPPED"

Andy
