### ISSUE TITLE
a special test file (85748k) cannot be printed through GCP

### ISSUE THREAD

**Issue by jiape** [google/cloudprint_logocert#144]
1.	Upload the test file to Google drive, it could not be opened in Google drive as below screenshot, and the print button is gray out at this moment.
2.	Try to print this test file with following steps on Mac OS, the test file can be uploaded successful, but finally it shows “Could not convert to PDF”. 
![googledrive_openerror](https://user-images.githubusercontent.com/30609495/33000646-5c34d940-cde4-11e7-9288-29d78bde841d.jpg)
![converttopdf_failed](https://user-images.githubusercontent.com/30609495/33000649-5d3934a8-cde4-11e7-99dc-f7778643af72.jpg)

That test file cannot be uploaded here since it's big than 10MB.

Thanks,
Andy

**Comment by kdlucas** [comment]
This is by design. There are hard limits to the size of files that can be printed.
