### ISSUE TITLE
print syntax in Python 3.5.1

### ISSUE THREAD

**Issue by tblossfeld** [google/cloudprint_logocert#17]
Hello,

When attempting to run the logo certification tool on a Windows machine, I am running into a problem where the Print statement requires parentheses. After doing some research, it appears this is a change from Python 2 to Python 3, though when exactly the change took place is unclear to me. I have attached a screen shot of an example where I am running the Python shell and attempt to use the print statement with and without (). 

![printsyntax](https://cloud.githubusercontent.com/assets/17885939/13822912/e275dc48-eb7d-11e5-93fb-b6de1d265b2f.png)

**Comment by kdlucas** [comment]
In this case, replace the interpreter to Python 2.x, and then it should work fine. We don't yet have support for Python 3.x. If you'd like to see Python 3.x, then file a feature request. 

Also, we're looking for more contributors in case anyone once to do the porting to 3.x.

**Comment by tblossfeld** [comment]
I would be willing to help with that once I am more familiar with the tool.
