### ISSUE TITLE
AttributeError: 'Nonetype '

### ISSUE THREAD

**Issue by tblossfeld** [google/cloudprint_logocert#18]
I have set up Windows with Python 2.7.x, and have installed all of the dependencies. I believe I have everything configured properly at this time, but when I try to run the tool I keep getting a "NoneType" error. I have attached a screenshot of the error. Can you provide any insight as to what might be causing this?

![error_nonetype](https://cloud.githubusercontent.com/assets/17885939/13993361/723cb3d8-f0f6-11e5-9cb9-cb359b38d8b2.png)

**Comment by kdlucas** [comment]
It looks like an element is not visible that it's looking for. In the beginning steps when it first sets up credentials you many need to do a manual step with the browser.

**Comment by tblossfeld** [comment]
Thanks. I noticed that I had not yet registered the device, and there was a problem with that. I have resolved it, but it has not cleared the error. The script seems to stop at the screen where it asks you to select a user account. I try selecting one of them, and I receive a redirect_uri_mismatch error. Attached is a screenshot of the error page. The url, in case that should be useful, is below:

https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudprint+https%3A%2F%2Fspreadsheets.google.com%2Ffeeds%2F&response_type=code&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&client_id=873159778538-irju3u707ve8806gm1fctsduaim1jmlh.apps.googleusercontent.com&hl=en&from_login=1&as=7aecc6b32ae126a9&authuser=0

![redirect_uri_mismatch](https://cloud.githubusercontent.com/assets/17885939/13997045/a22aba1c-f106-11e5-86b9-1938079a0c9f.png)

**Comment by kdlucas** [comment]
H'mmmm, it may be that you're using a browser that has multiple accounts associated with it. To resolve that, try going into Chrome's data directory and deleting it, so that no accounts are associated with the browser you are using to test with. For the Logo Cert Tool, it creates a directory in the directory where it runs, that is named identical to the user account (minus @gmail.com), so just delete that.

**Comment by tblossfeld** [comment]
Ok, thanks. I've tried this, but unfortunately, it didn't work. Incidentally, there were two accounts associated with it, but only because the tool asks for a 2nd user account. I haven't gotten to a point where it's actually used, though.

**Comment by tblossfeld** [comment]
It appears I either didn't have the configuration file correct (namely the gmail1, 2, and 3 links) or the client wasn't set up correctly. The first client I created was a Web Application. I created a new one as "Other". It's not explicitly stated in the README if this is correct.

**Comment by kdlucas** [comment]
Did your latest changes resolve the issue?

**Comment by tblossfeld** [comment]
I seem to have gotten past this issue, yes. Still having some other ones. When I create credentials for a 0Auth client id, can you confirm whether this should be "Web Application" or "Other" for Native applications?

**Comment by tblossfeld** [comment]
This issue is no longer occurring.
