### ISSUE TITLE
About testDeviceAcceptRegistration

### ISSUE THREAD

**Issue by YYWeave** [google/cloudprint_logocert#20]
Kelly

When we execute this test with our printer, according the message on the console as below. 

Verify printer must accept registration requests on printer panel. ... Validate if printer required user to accept registration request
If printer does not have accept/cancel on printer panel,
Fail this test.
Did the test produce the expected result?
Enter "y" or "n"

We have to fail this test manually(entered ‘n’), because our printer didn't have accept/cancel on printer panel. To fix this issue, we read the testcert.py source and found that it seems like this test is only printing out some messages. We think there should be registration execution like "chrome.RegisterPrinter(self.printer)".in the source of this test .
Could you please tell us the purpose of this test and let us know if there is something wrong with our understanding.

**Comment by kdlucas** [comment]
This is a manual test to verify that the printer has a way to accept and cancel registration requests, so this is just a manual verification that this mechanism is present on the printer.
