### ISSUE TITLE
HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by tblossfeld** [google/cloudprint_logocert#22]
I have gone over the setup and fixed a few issues I had with the config file. Unfortunately, when I run the test, I am hitting an Unauthorized error that I cannot seem to get past. Attached is a screenshot of the problem. Any thoughts on why this may be occurring?

![error_unauthorized](https://cloud.githubusercontent.com/assets/17885939/14176765/ad9eb4fa-f720-11e5-9c57-e038a0b9981a.png)

**Comment by kdlucas** [comment]
This makes me think that something in the data (line 126 or _oauth2.py) is not correct. This is constructed in lines 110-114 of the same file, and uses client_id, client_secret and refresh token. Make sure you downloaded the correct client_id and client_secret from the google developer console: console.developers.google.com

**Comment by tblossfeld** [comment]
Yes, I have verified this several times. Is it possible a blocked port could cause this? 

Incidentally, in your instructions, you say:

"Two tokens are needed: under Client ID for native applications, copy the Client ID and Client Secret"

I don't see anything in the Credentials page that actually says "native applications".

**Comment by kdlucas** [comment]
Do you see a credential with the name Native client? What name or names do
you see on the OAuth 2.0 client IDs page, under the Credentials tab?

Kelly
kdLucas

**Comment by tblossfeld** [comment]
Here are the options I see when I go to create a 0Auth Client

![credentials](https://cloud.githubusercontent.com/assets/17885939/14185600/a2d15eb0-f748-11e5-816f-b429f2c4fe35.png)

**Comment by kdlucas** [comment]
So it looks like you haven't created any client IDs yet. Go ahead and
select Web application and create one. Once it's created you can then
download it as a file to get both the id and secret.

Kelly
kdLucas

**Comment by tblossfeld** [comment]
I have created both a Web Application and an "Other" client. I have tried both with the same results. 

After talking to engineering, we may have some hard-coded credentials that have expired. This may be related.

**Comment by tblossfeld** [comment]
After doing some more research, I am wondering if I need to add "Authorized redirect URIs" to the client ID. I don't see any mention of this in the README file. Do I need to add something here, and if so, what would I be adding? (Below is a screenshot of the client ID circling the area I am talking about for clarification).

![authorization](https://cloud.githubusercontent.com/assets/17885939/14784912/e9a8196a-0ac5-11e6-928d-9b766cb496d5.png)

**Comment by kdlucas** [comment]
No Client redirects should be needed.

Kelly
kdLucas

**Comment by tblossfeld** [comment]
Digging more into this, it looks like I cannot access the authorization site. The address listed in the configuration file for this is:

OAUTH = 'https://accounts.google.com/o/oauth2/auth'
OAUTH_TOKEN = 'https://www.googleapis.com/oauth2/v3/token'

I have attempted to use these values with Postman, and am getting a log in error. If I use other values, such as github address, I do not get an error. 

Can you confirm that these values are correct?

**Comment by tblossfeld** [comment]
After updating to the latest version, I am no longer receiving this error. Closing this issue.
