### ISSUE TITLE
testLocalPrintingToggle() Failure

### ISSUE THREAD

**Issue by marctan** [google/cloudprint_logocert#23]
The failure is at line 2108 of testcert.py
The function was trying to find the change button from the chrome print dialog but this dialog is not visible/open, thus the test failed. 

I believe the print dialog box must be visible first before calling 'SelectPrinterFromPrintDialog()'.

@kdlucas and I already have an email thread about this issue.

Thanks
-Marc

**Comment by kdlucas** [comment]
Marc,

We made some changes to testcert.py, is this still an issue?

**Comment by marctan** [comment]
Kelly,

Unfortunately, this is still not fixed. 

I'm inserting our **previous original email thread** regarding this issue below for more information:

> **Marc**: My second concern is the testLocalPrintingToggle(). This test failed. The failure was on testcert.py:2108. It failed since it was trying to find the change button or (destination-settings-change-button) that does not exists. I believe the fix for this is, we should call chrome.Print() first before calling this line: 
> testcert.py:2108: found = chrome.SelectPrinterFromPrintDialog(self.printer, localprint=True)
> 
> 
> **Kelly**: For the 2nd issue, it shouldn't be calling chrome.Print() first, as the change button is not related to printing. When you're looking at the screen, do you see the Change button?
> 
> 
> **Marc**: The change button can be seen in the chrome "print dialog". Since we already closed the print dialog at line 2100 of testcert.py, the function chrome.SelectPrinterFromPrintDialog(self.printer, localprint=True) in line 2108 of testcert.py failed because it is expecting the "print dialog" to be there.  
> 
> **Kelly**: Marc, Ok, I understand better now. Please file an issue on GitHub and I'll address it there:
> 

Hope this helps.

Thanks,
Marc

**Comment by marctan** [comment]
Hello Kelly,

Do you have an update on this?

Thanks!

**Comment by kdlucas** [comment]
I think the fix here is simply to put chrome.print() in line 2107. I've made the change, so please verify if this works.

**Comment by marctan** [comment]
This is now fixed.

Thanks
