### ISSUE TITLE
Error in testPrintJpgDpiSetting()

### ISSUE THREAD

**Issue by marctan** [google/cloudprint_logocert#25]
This is the error: 
![testprintjpgdpisetting](https://cloud.githubusercontent.com/assets/19194749/15423878/8b64e9aa-1e4d-11e6-9c95-7681a33b8534.jpg)

testPrintJpgDpiSetting will call GetOptions(). 
GetOptions() should return a list of dpi option but it returned a boolean value 'False'. It failed at line chrome.py:671: `if not self.UploadFile(filename)` since filename '/tmp/testfile.jpg' does not exist.

**Comment by kdlucas** [comment]
I'm trying to remember the logic of how this method works. I clearly knew that the file did not exist, so it looks like this method would get the print dialog to open and then get the list of items in the a specific option. This used to work so I wonder if some logic has changed in Chrome that causes this to fail. Could you add some debug statements in the UploadFile method and see exactly where it's failing? I suppose we could use a real file for these methods.

**Comment by marctan** [comment]
Maybe there's some logic changes in Chrome. 
I've tried adding debug in 'UploadFile' method and it failed at:
```
if not self.cd.SendKeys(filename, input_file):
      return False
```

Hope this helps.

Thanks,
Marc

**Comment by kdlucas** [comment]
Yes, sorry I haven't spent much time in this code lately. I'll look at it
tonight and tomorrow and get some changes up.

Kelly
kdLucas

**Comment by marctan** [comment]
Hello Kelly,

Do you have an update on this?

Thanks!

**Comment by kdlucas** [comment]
Yes, I debugged this just now, and it's working as expected. I tested with version 51 of Chrome. If you want to debug this, run this by hand from a python shell:

import _chrome
import _chromedriver
import _log

logger = _log.GetLogger('LogoCert', logdir='/tmp/logocert', loglevel='debug', stdout=True)
chromedriver = _chromedriver.ChromeDriver(logger, '<username_here>', 5)
chrome = _chrome.Chrome(logger, chromedriver)

Now if it's working correctly, you should be able to do:

dpi_settings = chrome.GetOptions('dpi', '<printer_model>')

if it doesn't get them, execute:

print_button = chromedriver.FindName('cp-button-print')
chromedriver.ClickElement(print_button)
True
chrome.UploadFile('/tmp/testfile.jpg')
True
Verify those two commands return True. In my testing it returned True. I could then execute:

printer_found = chrome.SelectPrinter('<printer_model>')
items = chrome.GetMenuItems('dpi')
for item in items:
  print item.text

I then saw: 600 dpi

**Comment by marctan** [comment]
Kelly, I've tried to debug this using your code above on Chrome 51 and this is the result:

```
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import _chrome
>>> import _chromedriver
>>> import _log
>>>
>>> logger = _log.GetLogger('LogoCert', logdir='/tmp/logocert', loglevel='debug'
, stdout=True)
LogoCert DEBUG: Invocation started. Logger /tmp/logocert\LogoCert2016June23_1640
34.log
Logger Name: LogoCert
Log Mode: debug
>>> chromedriver = _chromedriver.ChromeDriver(logger, '', 5)
>>> chrome = _chrome.Chrome(logger, chromedriver)
>>> dpi_settings = chrome.GetOptions('dpi', '')
LogoCert ERROR: Error sending keys: /tmp/testfile.jpg
>>> print_button = chromedriver.FindName('cp-button-print')
LogoCert ERROR: Timed out looking for name: cp-button-print
>>>
```

Still the same error because the file does not exist. Maybe the file "/tmp/testfile.jpg" does exists on your end, that's why it does not fail.

**Comment by kdlucas** [comment]
I was able to reproduce the error, where ChromeDriver can't find 'cp-button-print'. I think this is what is leading to the error you are seeing.

From the command line I issued chromedriver.driver.get('https://www.google.com/cloudprint') and then after that chromedriver could find 'cp-button-print'. So this makes me think that Chrome is getting to a state where chromedriver is unable to find the name we are looking for. I may need to put a simple chromedriver.driver.get() command before we do a search for the name.

**Comment by kdlucas** [comment]
I just looked at the code in _chrome.py and I do see it's issuing a cd.driver.get() right before it searches for the name 'cp-button-print', so it may be that I need to put a couple of second delay in here in case the page doesn't refresh fast enough. Once it finds the name 'cp-button-print' the UploadFile() method works fine, even with a non-existent file.

**Comment by marctan** [comment]
Hi Kelly,

Thanks for investigating this. 


I've tried calling the chromedriver.driver.get and here's what I got: 

```
Type "help", "copyright", "credits" or "license" for more information.
>>> import _chrome
>>> import _chromedriver
>>> import _log
>>> logger = _log.GetLogger('LogoCert', logdir='/tmp/logocert', loglevel='debug'
, stdout=True)
LogoCert DEBUG: Invocation started. Logger /tmp/logocert\LogoCert2016July18_0943
32.log
Logger Name: LogoCert
Log Mode: debug
>>> chromedriver = _chromedriver.ChromeDriver(logger, '', 5)
>>> chrome = _chrome.Chrome(logger, chromedriver)

>>> chromedriver.driver.get('https://www.google.com/cloudprint')
>>> print_button = chromedriver.FindName('cp-button-print')
>>> chromedriver.ClickElement(print_button)
True
>>> chrome.UploadFile('/tmp/testfile.jpg')
LogoCert ERROR: Error sending keys: /tmp/testfile.jpg
False
>>>
```


As you can see above, the 'cp-button-print' error is gone. But after executing UploadFile(), I'm still seeing a Failure. 'LogoCert ERROR: Error sending keys: /tmp/testfile.jpg'.

**Comment by kdlucas** [comment]
Well, that is really weird. I ran exactly the same commands, and when I run chrome.UploadFile('/tmp/testfile.jpg') 

It opens the print dialog and returns true. The print dialog at this point is opened where I need to select a printer. I'm looking at the code for _chrome.UploadFile() and I don't see where this error message would get generated "Error sending keys", unless it's failing in line 608 --> if not self.cd.SendKeys(filename, input_file):

Are you running this on Windows? If so, I wonder if it doesn't like a reference to /tmp .

**Comment by marctan** [comment]
In my case after executing chrome.UploadFile('/tmp/testfile.jpg') it shows "Select a file from computer" screen as you can see from below image:

![selectfile](https://cloud.githubusercontent.com/assets/19194749/17052919/1b4928f4-5032-11e6-80dc-22f353aa33f4.png)



It doesn't get to the point where the print dialog box is open like your scenario

I'm using Windows 7. 

And yes it's failing in line 608:
I've tried adding debug in 'UploadFile' method and it failed at:

```
if not self.cd.SendKeys(filename, input_file):
       return False
```

**Comment by kdlucas** [comment]
Marc,

Can you change "/tmp/filename" to something that Windows uses and would
understand, like "C:\\Users\Pulic\testfile" or something that exists
(except the actual file). I'm curious if this will get us to the Print
Dialog.


Kelly
kdLucas

**Comment by kdlucas** [comment]
If it continues to be an issue we'll try using a real file and see if that fixes this edge case. An interesting data point is that this hasn't been reported by anyone else, so I'm guessing it's OS related.

**Comment by marctan** [comment]
Kelly,

I've tried using **( 'C:/testfile.jpg')** and it's now working fine. I think you're correct that windows don't understand the "/tmp/filename" dir. 

Below are the complete commands:

```
>>> import _chrome
>>> import _chromedriver
>>> import _log
>>> logger = _log.GetLogger('LogoCert', logdir='/tmp/logocert', loglevel='debug'
, stdout=True)
LogoCert DEBUG: Logger LogoCert is already intialized
>>> chromedriver = _chromedriver.ChromeDriver(logger, '', 5)
>>> chrome = _chrome.Chrome(logger, chromedriver)
>>> chromedriver.driver.get('https://www.google.com/cloudprint')
>>> print_button = chromedriver.FindName('cp-button-print')
>>> chromedriver.ClickElement(print_button)
True
>>> chrome.UploadFile('C:/testfile.jpg')
True
>>> printer_found = chrome.SelectPrinter('')
LogoCert ERROR: Error clicking element.
>>> items = chrome.GetMenuItems('dpi')
>>> for item in items:
...     print item.text
...
4800 CQ
1200 dpi
>>>
```

**Comment by kdlucas** [comment]
Ok, I'll make a change that will differentiate between OS, and provide a
pathname that it understands.

Kelly
kdLucas

**Comment by kdlucas** [comment]
Ok, I made the changes. Let me know if that works. I wonder if I should actually use a real file here and not a fake file.

**Comment by YasuhiroFuruta** [comment]
We confirmed this fix works fine.

**Comment by marctan** [comment]
Working now. Thanks
