### ISSUE TITLE
Error in testPrintJpgLarge()

### ISSUE THREAD

**Issue by marctan** [google/cloudprint_logocert#26]
This test will try to print a large .JPG photo but failure occured during file upload.
Refer to image below:

![error during upload](https://cloud.githubusercontent.com/assets/19194749/15424385/5568e1b4-1e50-11e6-8283-480a2a530514.jpg)

**Comment by kdlucas** [comment]
What version of Chrome are you using? I wonder if you change the Chrome version if it will be able to convert the file.

**Comment by marctan** [comment]
There's a chance that the internet connection was slow when I performed this test. I've retest this today and it's already printing.

**Comment by kdlucas** [comment]
I wouldn't expect a slow Internet connection to affect this conversion, as I think this is an internal conversion using Chrome. It's quite possible that Chrome performed and update and that resolved the issue. One way to learn more about this kind of error in Chrome is to turn on the debug log (start Chrome with the arguments: --enable-logging --v=1 ) and then this log will get created under the user profile in a file called chrome_debug.log:

https://www.chromium.org/for-testers/enable-logging

I'll close this issue for now.
