### ISSUE TITLE
GCP Logo Certification Automation tests: Resolved Issues in Printer Capabilities

### ISSUE THREAD

**Issue by surenderkodam** [google/cloudprint_logocert#31]
If the Resolved Issue field is empty, then the automation test is failing but it is expected to pass as  per behavior of GCP 2.0 specification.

**Comment by kdlucas** [comment]
The test should pass if resolvedIssue field is present, as the test does not look for any value, only that the field is present.

**Comment by surenderkodam** [comment]
Yes, I have added an if condition. Change has been committed.
