### ISSUE TITLE
testLocalPrintUpdateMgtPage() Failure

### ISSUE THREAD

**Issue by marctan** [google/cloudprint_logocert#34]
There are two ways to access the list of "Print Job". 
Please see the screenshot below to clearly understand the problem:

This is the first way. Let's call this **'Print Jobs 1'** 
![print jobs without filter](https://cloud.githubusercontent.com/assets/19194749/16335642/4e478bf0-3a3a-11e6-91c5-0e969e4ad5ff.jpg)

The second way is by clicking the 'show print jobs' shown below. Let's call this **'Print Jobs 2'**
![print jobs inside printers](https://cloud.githubusercontent.com/assets/19194749/16335659/64c0ea84-3a3a-11e6-9fde-6ea8e4f48c2e.jpg)

During printing locally, the print job gets submitted using the printer's robot account. So the print job will not show under **'Print Jobs 1'.** But it will show under **'Print Jobs 2'.**

If I'm not mistaken all print job showing in **"Print Jobs 1"** are jobs that belongs to me, that is, ownerId: marctan@lexmark.com.

All print jobs showing in **"Print Jobs 2"** are job that belongs to all user **including the robot account** under that specific printer.

As what you've said  (@kdlucas) from our previous email thread, when printing locally, the printer's robot account is used as an ownerId 
(e.g 3c1c01d118ceef296e07026446e97a05@cloudprint.googleusercontent.com) so it is expected that it will not show in 'Print Jobs 1'

The problem is, the **new gcp automation test script (testLocalPrintUpdateMgtPage)** is expecting the job to show under "Print Jobs 1". 

I think the test script must be modified to expect from **"Print Jobs 2"** when printing locally not from "Print Jobs 1"

-Marc

**Comment by kdlucas** [comment]
If memory serves me correctly, I think this was a case when the printer
would need to send additional commands to our service in order to get this
print job associated with the right user. However, I think there is a
chance that anonymous users can send local print jobs, which invalidates
this test.

I may just remove this test since it's not blocking for logo certification.

**Comment by YasuhiroFuruta** [comment]
I implemented the Marc's idea.
Please review it.
