### ISSUE TITLE
Media sensor option in CAPS

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#36]
Currently media sensor test(e.g. "testNoMediaInTray") is enabled if the tray sensor option ("TRAY_SENSOR") is set.
However, some printers have either a media sensor or a tray sensor.
(e.g. a low-end inkjet printer that has one rear feeder supports a media sensor only.)

I think a new option for the media sensor test is needed in CAPS.

**Comment by kdlucas** [comment]
What is the difference between the tray sensor and the media sensor? Is the
media sensor for printers that don't have a try, meaning you must manually
place paper in the rear feeder?

Kelly
kdLucas

**Comment by YasuhiroFuruta** [comment]
No. (except for manual feeders)

The tray sensor means the tray **open** sensor.
The media sensor means the media **empty** sensor.

Almost rear feeder has no **open** sensor, because it cannot be opened.

Sorry for the confusing explanation.
