### ISSUE TITLE
Copies option for local printing in CAPS

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#37]
Currently, copies setting tests are enabled/disabled by one option ("COPIES") for both cloud printing and local printing.
However, some printers support the copies setting only for cloud printing, and does not support it for local printing, because they can not store entire print data on their memory.

I suggest splitting the option into two options for cloud printing and local printing.

**Comment by kdlucas** [comment]
That's a good idea as I know many printers don't support copy option for
local printing.

Kelly
kdLucas
