### ISSUE TITLE
Local printing availability under unregistered state

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#38]
It's recommended that local printing is available only if the printer is registered because the document says "a newly connected device should only support the /register api" in [Cloud Print]->[GUIDES]->[Privet Local Discovery]->[4.2. /privet/info API], and many printers support the recommendation.
However, the following test cases expect that local printing is available even if the printer is unregistered.
- testPrivetAccessTokenAPI
- testPrivetCapsAPI
- testPrivetPrinterAPI
- testLocalPrintGuestUserUnregisteredPrinter

I think these test cases should be removed.

**Comment by YasuhiroFuruta** [comment]
We should set True to the 'LOCAL_PRINT' option in CAPS to skip these test cases,
if the printer do not supports local printing before the printer is registered.

This option for local printing under UNREGISTERED state ONLY,
and it's NOT effective for local printing under registered state.

It is described in 'README' and '_config.py'.

**Comment by kdlucas** [comment]
Right, some tests should only run if the printer supports local printing
before it's registered.

Kelly
kdLucas
