### ISSUE TITLE
testPrinterName() should be used the PRINTER['NAME'] value

### ISSUE THREAD

**Issue by YoshimiMorita** [google/cloudprint_logocert#39]
The test case "testPrinterName" is checking the printer name using the Constants.PRINTER['MODEL'].

However the printer-name has been separated as 'NAME' from 'MODEL' in PRINTER.

I think that this test case should be used the Constants.PRINTER['NAME'].

**Comment by kdlucas** [comment]
Yes, we just added a new key for Printer name. I'll take a look and see if
it makes sense to change this, since it's possible that there are more than
one of the same model on the local network.

Kelly
kdLucas

**Comment by kdlucas** [comment]
This has been fixed.
