### ISSUE TITLE
Workaround for local printing layout issue of Chrome

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#40]
Many printers do not send the "page_orientation" field in CDD because of the instructions of Google.
However, the Chrome browser does not display the layout setting if there is no "page_orientation" field in CDD.

I suggest skipping the test case "testLocalPrintLayout" for temporary workaround, if "LAYOUT_ISSUE" option is False in CAPS.

**Comment by kdlucas** [comment]
Yes, I think that might work.

Kelly
kdLucas
