### ISSUE TITLE
'Printer' 'Port' field recognized as string instead of number

### ISSUE THREAD

**Issue by tblossfeld** [google/cloudprint_logocert#47]
I am running the updated script, and am running into an error where the script thinks device_port is a string instead of a number. I have set this variable as '6006' in the config file. Error is seen here:

![setupmodule](https://cloud.githubusercontent.com/assets/17885939/16739480/5362740c-4768-11e6-82b2-a2c94f071a68.png)

**Comment by kdlucas** [comment]
I think this should be an integer.

Kelly
kdLucas

**Comment by kdlucas** [comment]
I just updated the comments in _config.py to indicate port is an integer
value.

Kelly
kdLucas

**Comment by kdlucas** [comment]
Just set printer port to 6006, not '6006', or let the script automatically update the printer port, as it will try to use MDNS traffic to get the correct port number.
