### ISSUE TITLE
testPrintJpgLarge() Failure

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#49]
This test case fails because 'GoogleArt.jpg' cannot be printed from the Cloud Print management page.
In this time the server says "Could not convert to PDF.".

I think 'GoogleArt.jpg' is too large to print from the Cloud Print management page.

Does anyone know the maximum size which is acceptable from the Cloud Print management page?

**Comment by kdlucas** [comment]
It should be able to be converted. If you're seeing "Could not convert to PDF", it's possible something has changed on our backend that no longer works to convert this file. The max size of an image used to be 40mb, but I'm not sure what it is now. This test used to work fine, so maybe something has changed. I'll need to look into it.

**Comment by kdlucas** [comment]
We just found out our team that does file conversions have reduced the size to 20 Mb. We have filed a bug with them as it used to be 40Mb. I'll update this issue once we hear back from this team.

**Comment by kdlucas** [comment]
I've confirmed that the back end conversion engine only accepts up to 20MB file size. I'm now waiting to see if this limit will change or remain in force. If it remains, then we'll need to find a new JPG file that is less than 20MB in size.

**Comment by kdlucas** [comment]
Ok, the conversion team has increased the max file size to 40mb. Could you confirm that you are able to print this file using Google Cloud Print.

**Comment by YasuhiroFuruta** [comment]
This issue is not fixed yet.

It seems image that have over 25M pixel is rejected by the server.
A 1,000px x 25,000px JPEG image is accepted.
A 1,000px x 25,001px JPEG image is reject.

**Comment by kdlucas** [comment]
Yes, you're right, there is also a hard limit of 5,000 x 5,000 pixels. I'm asking to increase this limit now.

**Comment by kdlucas** [comment]
Updated the label since this technically is not a bug within our testing code. We are attempting to get this updated in our conversion server to handle larger file sizes and more pixels per image.

**Comment by kdlucas** [comment]
Looks like the fix is targeted to be pushed on Sept 26. I'll update when I verify the fix.

**Comment by YasuhiroFuruta** [comment]
We confirmed this issue has been fixed.
The server accepts 'GoogleArt.jpg' and it is printed.
