### ISSUE TITLE
About testOpenPaperTray() and testNoMediaInTray()

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#53]
testOpenPaperTray() and testNoMediaInTray() expect that an error icon (red) is displayed on the management page when a tray is open or empty.
However the management page displays a warning icon (yellow) for some printer which can accept jobs in that state.

I think both the error icon and the warning icon should be acceptable in these test cases.

**Comment by kdlucas** [comment]
I agree. I'll update the tests.

Kelly
kdLucas

**Comment by YasuhiroFuruta** [comment]
Sorry, I had overlooked about the tray empty state.

When the tray is open, warning icon is displayed in both Printers page and the Printer Details page.
It has been resolved by #55.

However, when the tray is empty, warning icon is displayed only in the Printer Details page.
So testNoMediaInTray() should check the Printer Details page.

**Comment by marctan** [comment]
I agree with Yasuhiro. This tests also failed on our printers since we report warnings not errors when tray is open and when there's no media in tray.

**Comment by kdlucas** [comment]
Merged fix with main branch. Hopefully this fixes issues that people have.

**Comment by YasuhiroFuruta** [comment]
testNoMediaInTray() has not been fixed yet.
