### ISSUE TITLE
Error in testLocalPrintNotOwner()

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#54]
This test case fails to create 2nd ChromeDriver object.
The following message is displayed in the console.

```
Verify local print available to non owner of printer. ... [9072:1224:0727/130844:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[9072:1224:0727/130844:ERROR:cache_util.cc(134)] Unable to move cache folder ...\cloudprint_logocert-master\<USER2>\ShaderCache\GPUCache to ...\cloudprint_logocert-master\<USER2>\ShaderCache\old_GPUCache_000
[9072:1224:0727/130844:ERROR:cache_creator.cc(129)] Unable to create cache
[9072:1224:0727/130844:ERROR:shader_disk_cache.cc(589)] Shader Cache Creation failed: -2
```

Our environment follows:
Chrome: 52.0.2743.82 m
ChromrDriver: 2.22.397933
Python: 2.7.10
OS: Windows 7 Pro SP1 (64bit)

**Comment by YasuhiroFuruta** [comment]
testLocalPrintNotOwner() fails to create the 2nd ChromeDriver object because the 2nd Chrome window has been opened.

It seems User2RegistrationAttempt() does not close the 2nd Chrome window when this test case cannot register the printer (test result is 'Blocked').
User2RegistrationAttempt() should close the 2nd Chrome window always.

**Comment by kdlucas** [comment]
I wonder if this is something Windows specific? I wonder why it's trying to
move the cache on Chrome. It looks like it tries to close Chrome in line
2065.

Kelly
kdLucas

**Comment by YasuhiroFuruta** [comment]
This error occurs because two Chrome instances using the same profile folder.
So it's not Windows specific.

When Chrome browser is starting up, it move a GPU cache folder, to delete the folder background.
[https://chromium.googlesource.com/chromium/src/net/+/master/disk_cache/cache_util.cc](url)

Line 2065 in 'testcert.py' is unexecuted yet, because this error occurs at the line 2050.

User2RegistrationAttempt() does not close the 2nd Chrome, if chrome2.RegisterPrinter() returns False.
The 2nd chrome remains and it triggers this error when testLocalPrintNotOwner() is executed.
```
    if chrome2.RegisterPrinter(self.printer):
      registered = chrome2.ConfirmPrinterRegistration(self.printer)
      try:
        self.assertFalse(registered)
      except AssertionError:
        notes = 'A simultaneous registration request registered a printer!'
        self.LogTest(test_id, test_name, 'Failed', notes)
        raise
      else:
        notes = 'Simultaneous registration request was not successful.'
        self.LogTest(test_id, test_name, 'Passed', notes)
      finally:
        **cd2.CloseChrome()**
    else:
      notes = 'Error attempting to register printer by %s' % (
          Constants.USER2['EMAIL'])
      self.LogTest(test_id, test_name, 'Blocked', notes)
```

**Comment by kdlucas** [comment]
It should actually be USER2's profile, not the same as USER. As long as USER2 is set up then cd2 should be another instance of Chrome using another profile. They should be using different directories for each profile (USER and USER2).

**Comment by YasuhiroFuruta** [comment]
User2RegistrationAttempt() opens Chrome using USER2's profile, and it does not close this Chrome window on some cases.
After that, testLocalPrintNotOwner() opens Chrome using USER2's profile too, and this error occurs.

(Of course, Chrome using USER1's profile is opened apart from that.)

```
  def User2RegistrationAttempt(self):
    """Verify multiple registration attempts are not allowed by device."""
    test_id = '923ee7f2-c337-49d4-aa4d-8f8e3b43621a'
    test_name = 'testMultipleRegistrationAttempt'
    data_dir = Constants.USER2['EMAIL'].split('@')[0]
    cd2 = _chromedriver.ChromeDriver(logger, data_dir, self.loadtime)
```

```
  def testLocalPrintNotOwner(self):
    """Verify local print available to non owner of printer."""
    test_id = 'ea9b1e01-f792-4627-bf84-2db5db513da4'
    test_name = 'testLocalPrintNotOwner'
    data_dir = Constants.USER2['EMAIL'].split('@')[0]
    cd2 = _chromedriver.ChromeDriver(logger, data_dir, self.loadtime)
```

**Comment by kdlucas** [comment]
That's the issue, if the Chrome window does not get closed. I think we need
to figure out how to ensure the Chrome Window gets closed for all previous
tests.

Kelly
kdLucas
