### ISSUE TITLE
Printer dialog is not opened for [testLocalPrintGuestUserUnregisteredPrinter]

### ISSUE THREAD

**Issue by SatsukiHana** [google/cloudprint_logocert#60]
Logocert package : google-cloudprint_logocert-ec173f9
test_id = '6e75edff-2512-4c7b-b5f0-79d2ef17d922'
test_name = 'testLocalPrintGuestUserUnregisteredPrinter'

I think this test suppose to open print dialog.
Manually adding "chrome3.Print()" works ok.

Please confirm. Thanks.

**Comment by kdlucas** [comment]
Yes, Print() needs to be called. Fixed.
