### ISSUE TITLE
Sleep timer update request for [testDeviceOffPowerOnAdvertisePrivet]

### ISSUE THREAD

**Issue by SatsukiHana** [google/cloudprint_logocert#61]
Chrome browser does not refresh previously discovered local printer list in 60 seconds but sleep timer is set to 60 seconds for this test.
Can you consider updating this value to 120 in order to give enough time for Chrome browser to refresh a printer list?

Test tool: google-cloudprint_logocert-a034a70
test_id = '35ce7a3d-3403-499e-9a60-4d17e1693178'
test_name = 'testDeviceOffNoAdvertisePrivet'

**Comment by kdlucas** [comment]
Ok, I've removed the hard coded value and added a class variable sleep_time, and have increased it to 120 seconds.
