### ISSUE TITLE
GCP Logo Certification GitHub Tool: LocalPrintUpdateMgtPageLocal testcase issue

### ISSUE THREAD

**Issue by surenderkodam** [google/cloudprint_logocert#72]
testLocalPrintUpdateMgtPage
We think that the LogoCert tools has checked to the wrong web page.
Printer can be found on the following page:
[Mgmt Page]

  .'Printer' -> choose the printer -> 'Show Print Jobs'

**Comment by surenderkodam** [comment]
https://github.com/google/cloudprint_logocert/commit/ceb230ecc3ee7aac44abfbccf997ed06464c72cb

**Comment by YasuhiroFuruta** [comment]
I think PR #70 is better than https://github.com/google/cloudprint_logocert/commit/ceb230ecc3ee7aac44abfbccf997ed06464c72cb, because https://github.com/google/cloudprint_logocert/commit/ceb230ecc3ee7aac44abfbccf997ed06464c72cb makes multiple test cases slow.
