### ISSUE TITLE
testPrintFilePdfColorTicket() Failure

### ISSUE THREAD

**Issue by marctan** [google/cloudprint_logocert#79]
The printout of this test scenario should be in LANDSCAPE but it's not. So we marked it as failure.

I've checked the testscript and noticed that "layout" parameter was not passed when calling chrome.PrintFile(). As you can see from below snippet:
```
def testPrintFilePdfColorTicket(self):
    """Test printing PDF file of Color Ticket in landscape orientation."""
    test_id = '4bddcf56-984b-4c4d-9c39-63459b295247'
    test_name = 'testPrintFilePdfColorTicket'
    logger.info('Printing PDF Color ticket in with landscape orientation.')
    output = chrome.PrintFile(self.printer, Constants.IMAGES['PDF2'],
                              color=self.color)
``` 

I've tried adding layout='LandScape'  and it's working as it should. It printed in Landscape format. 
```
output = chrome.PrintFile(self.printer, Constants.IMAGES['PDF2'],
                              color=self.color,layout='Landscape')
```

Can you please add this change to the testscript? Thanks!

**Comment by kdlucas** [comment]
Now layout is specified.
