### ISSUE TITLE
ERROR: setUpModule (__main__)

### ISSUE THREAD

**Issue by KellyML** [google/cloudprint_logocert#85]
Hello~ I am getting an error in the setUpModule as seen here, please help to check it.
![2016-10-19 11 46 54](https://cloud.githubusercontent.com/assets/22831638/19505162/d4279f30-95f2-11e6-985a-27e5c4a4dc50.png)

**Comment by kdlucas** [comment]
That's odd, have you installed Chromedriver?

**Comment by KellyML** [comment]
Yes, i had install ChromeDriver by the following steps:

sudo apt-get install unzip
wget -N http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux32.zip
unzip chromedriver_linux32.zip
chmod +x chromedriver
sudo mv -f chromedriver /usr/local/share/chromedriver
sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver

besides, the "Chrome://Version" page would be pop-up as below:
![2016-10-19 16 45 24](https://cloud.githubusercontent.com/assets/22831638/19511802/7c242866-961b-11e6-8dff-7613a7947860.png)

**Comment by kdlucas** [comment]
Can you try running the string of commands from the Python interpreter, and then right before you get to this line of code, see what keys are available for chromedriver.driver.__dict__['capabilities']['chrome'] ? I wonder if this is some change that we are seeing on Windows.

**Comment by KellyML** [comment]
sorry for the response so late, 
i try to install ChromeDriver again, and put the chromedriver binary in the path, then the issue would not occurred. 

but i met another issue as below:  
LogoCert ERROR: Timed out finding XPaths: //*[contains(text(), "Details")]
LogoCert ERROR: Error finding details button on printer page.

do the LogoCert can't find the "Details" button in chinese? 

![screenshot from 2016-10-21 14 24 56](https://cloud.githubusercontent.com/assets/22831638/19588797/a755ad4a-979a-11e6-9aa1-4493217bc548.png)

**Comment by kdlucas** [comment]
I'm not sure if it will find it if it's in Chinese. To know for sure, navigate to this page and open developer tools and see what this web element looks like. My guess is that in Chinese it may be some double byte encoded characters, and not "Details". You may need to run this using English language.

**Comment by KellyML** [comment]
Change to English language is OK.
