### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'si_displayed'

### ISSUE THREAD

**Issue by KellyML** [google/cloudprint_logocert#86]
Hello, when i run the "testcert.py" would met : AttributeError: 'NoneType' object has no attribute 'si_displayed'
and chrome would show: Error redirect_uri_mismatch
please help me to check it, thanks~

![error_msg](https://cloud.githubusercontent.com/assets/22831638/19641805/fa3dedde-9a14-11e6-87aa-12bdfa73bc7c.JPG)
![error_http](https://cloud.githubusercontent.com/assets/22831638/19641809/01aa9ebe-9a15-11e6-871c-27bacb8b5322.JPG)

**Comment by kdlucas** [comment]
Looks like we may need to change a value in the _config.py file. The section AUTH['REDIRECT'] is set to AUTH['REDIRECT']: 'urn:ietf:wg:oauth:2.0:oob', and looks like it no longer allows for that as a redirect URL for a web application. Try changing this value to something like https://www.google.com/cloudprint, and make sure it matches what you have set on the developer console.

**Comment by KellyML** [comment]
We found it looks like the "Application type" of "Create client ID" issue, only select the "Other" item, then the "redirect_uri_mismatch" error just not occurred.

![screenshot from 2016-10-25 17 19 54](https://cloud.githubusercontent.com/assets/22831638/19680385/0a46a3ec-9ad8-11e6-8c50-66425456611d.png)

**Comment by kdlucas** [comment]
Ok, we can close this issue.
