### ISSUE TITLE
GCP Server can register and cannot print any jobs always queue now.

### ISSUE THREAD

**Issue by iamoklo** [google/cloudprint_logocert#88]
Yes, our Xerox Phaser 6022 was GCP 2.0 logo certified. But nearly a month to maintain test, we found the printer can register and cannot print jobs.
The root cause is that the type of “numberOfPages” field returned by the /jobs interface is changed. Our code checks that it should be a integer value,
but the value returned now is a string. See below the red line:
 
{
"success": true,
"request": {
  "time": "0",
  "params": {
   "printerid": [
    "a3d31a69-99fd-1d22-91d1-7d6f429f94da"
   ]
  },
  "user": "dennisdeveloper2015@gmail.com",
  "users": [
   "dennisdeveloper2015@gmail.com"
  ]
},
"xsrf_token": "AIp06DgIDmkZzhNapOyc5B8MxA7AwLRjNw:1474420393626",
"jobs": [
  {
   "ticketUrl": "https://www.google.com/cloudprint/ticket?jobid\u003ddcdd5323-b309-4641-fdba-6f49ea1a2bcf",
   "printerType": "GOOGLE",
   "printerName": "Dell Color MFP E525w (60:C7:EA)",
   "errorCode": "",
   "updateTime": "1474420274394",
   "title": "zlib.3.pdf",
   "message": "",
   "ownerId": "dennisdeveloper2015@gmail.com",
   "tags": [
    "^own",
    "print_file",
    "dashboard"
   ],
   "uiState": {
    "summary": "QUEUED",
    "progress": "Delivery attempts: 1"
   },
    "numberOfPages": "2",
   "createTime": "1474420273306",
   "semanticState": {
    "delivery_attempts": 1,
    "state": {
     "type": "QUEUED"
    },
    "version": "1.0"
   },
   "printerid": "a3d31a69-99fd-1d22-91d1-7d6f429f94da",
   "fileUrl": "https://www.google.com/cloudprint/download?id\u003ddcdd5323-b309-4641-fdba-6f49ea1a2bcf",
   "id": "dcdd5323-b309-4641-fdba-6f49ea1a2bcf",
   "rasterUrl": "https://www.google.com/cloudprint/download?id\u003ddcdd5323-b309-4641-fdba-6f49ea1a2bcf\u0026forcepwg\u003d1",
   "contentType": "application/pdf",
   "status": "QUEUED"
  }
],
"range": {
  "jobsTotal": "1",
  "jobsCount": 1
}
}
 
The printer check type failed, so it cannot print jobs.
 
Is it caused by GCP server updates or modify?
Have you got specification description of the JSON response of the /jobs interface?
![noname](https://cloud.githubusercontent.com/assets/22787996/19710902/53138aae-9b64-11e6-9085-a9ecc260f67e.jpg)

**Comment by kdlucas** [comment]
I'm checking on this, but you should talk to the Google Cloud Print team, as it's not an issue with the Logo Cert Tool.
