### ISSUE TITLE
Auth token expiration 

### ISSUE THREAD

**Issue by lrbom** [google/cloudprint_logocert#98]
Auth tokens have a shelf time of 1 hour before expiration. Currently, the token is refreshed at the beginning of every test suite (aside form CloudPrinting, since it's a long testsuite, token refresh is handled before each test case) .

Since users may very well be occupied with other tasks between test cases, this error could occur every now and then. We should be able to refresh auth tokens when we detect that they are expired instead of failing.

**Comment by kdlucas** [comment]
I'm trying to think of a good way to check for this. It seems like performing a check before each test is overkill and may degrade performance. I wonder if there is a way to spawn a separate thread whose sole responsibility is to ensure the Auth Token is current.
