### ISSUE TITLE
logocert_api branch: Get_service_ttl (_zconfig.py)

### ISSUE THREAD

**Issue by YoshimiMorita** [google/cloudprint_logocert#99]
Hi Kelly-san/GCPTeam,

I'm trying the test tool 2.0.

I faced an issue in the testPrinterIdleNoBroadcastPrivet() test.

In the Get_service_ttl() function (_zconfig.py), 
it checking service_name and Constants.PRINTER['NAME'] using startswith.

I think that it should be used the partial comparison (such as 'in'), as wait_for_service_add().
Please confirm it.

Regards,
Yoshimi Morita

**Comment by lrbom** [comment]
Hi Yoshimi,

I agree that both of those functions should use have the same comparison strictness.
I have updated Get_service_ttl() to use 'in' instead of 'startswith'.
Please pull from logocert_api to get the this change .

Thanks for trying out the tool!

Kevin

**Comment by YoshimiMorita** [comment]
Hi Kevin-san,

I confirm this change, it works well.
I sincerely appreciate your swift action.

This issue was fixed. I will close this.

Regards,
Yoshimi Morita
